# Generated by Django 4.2.26 on 2025-12-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                (
                    "guessed_letters",
                    models.CharField(blank=True, default="", max_length=26),
                ),
                ("incorrect_guesses", models.IntegerField(default=0)),
                ("max_incorrect_guesses", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InProgress", "InProgress"),
                            ("Won", "Won"),
                            ("Lost", "Lost"),
                        ],
                        default="InProgress",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
